#!/usr/bin/env python3
"""Collect corresponding sources and build recipes for a qualified Unix runtime."""
import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import tarfile
from urllib.parse import quote, urlparse
from urllib.request import Request, urlopen


def sha256(path):
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def download(entry, directory):
    name = Path(urlparse(entry["url"]).path).name
    path = directory / (entry["sha256"][:16] + "-" + name)
    if not path.exists() or sha256(path) != entry["sha256"]:
        temporary = path.with_name(path.name + ".partial")
        url = entry["url"].replace("https://ftpmirror.gnu.org/gnu/", "https://ftp.gnu.org/gnu/")
        subprocess.run(["curl", "--fail", "--location", "--retry", "3", "--connect-timeout", "30",
                        "--max-time", "600", "--silent", "--show-error", url, "--output", str(temporary)], check=True)
        if sha256(temporary) != entry["sha256"]:
            raise RuntimeError(f"Source checksum mismatch: {entry['url']}")
        temporary.replace(path)
    print("Verified source:", name, flush=True)
    return dict(entry, file=path.name)


def macos(notices, sources):
    entries = {}
    for package in sorted(notices.iterdir()):
        sbom_path = package / "sbom.spdx.json"
        sbom = json.loads(sbom_path.read_text()) if sbom_path.exists() else {"packages": []}
        receipt = json.loads((package / "INSTALL_RECEIPT.json").read_text())
        built_at = sbom.get("creationInfo", {}).get("created") or datetime.fromtimestamp(receipt["time"], timezone.utc).isoformat()
        found = False
        for item in sbom["packages"]:
            url = item.get("downloadLocation", "")
            if not url.startswith(("https://", "http://")) or "ghcr.io/" in url:
                continue
            digest = next(c["checksumValue"] for c in item["checksums"] if c["algorithm"] == "SHA256")
            entries[digest] = dict(package=package.name, url=url, sha256=digest)
            found = True
        for recipe in (package / "homebrew-recipes").glob("*.rb"):
            content = recipe.read_text()
            # Literal source/resource/patch URLs with pinned checksums.
            for url, digest in re.findall(r'\burl "([^"]+)"[^\n]*\n(?:\s*(?:mirror|version) [^\n]+\n)*\s*sha256 "([a-f0-9]{64})"', content):
                entries[digest] = dict(package=package.name, url=url, sha256=digest)
                found = True
            # Readline's upstream patch series is generated by the formula.
            if "patch_checksum_pairs = %w[" in content:
                pairs = re.findall(r"^\s+(\d{3}) ([a-f0-9]{64})$", content, re.M)
                template = re.search(r'url "([^"]+#[{]p[}][^"]*)"', content).group(1)
                for number, digest in pairs:
                    entries[digest] = dict(package=package.name, url=template.replace("#{p}", number), sha256=digest)
            # Homebrew-managed patches are read from their last revision at build time.
            for patch in re.findall(r'\bfile "(Patches/[^"]+)"', content):
                endpoint = "https://api.github.com/repos/Homebrew/homebrew-core/commits?path=" + quote(patch)
                endpoint += "&until=" + quote(built_at) + "&per_page=1"
                with urlopen(Request(endpoint, headers={"User-Agent": "mocktave-source-collector"}), timeout=60) as response:
                    commits = json.load(response)
                if not commits:
                    raise RuntimeError(f"Cannot resolve Homebrew patch at build time: {patch}")
                revision = commits[0]["sha"]
                url = f"https://raw.githubusercontent.com/Homebrew/homebrew-core/{revision}/{patch}"
                with urlopen(url, timeout=60) as response:
                    data = response.read()
                digest = hashlib.sha256(data).hexdigest()
                entries[digest] = dict(package=package.name, url=url, sha256=digest, homebrew_revision=revision)
        if not found:
            raise RuntimeError(f"No pinned corresponding source for {package.name}")
    with ThreadPoolExecutor(max_workers=4) as pool:
        return list(pool.map(lambda entry: download(entry, sources), entries.values()))


def linux(notices, sources):
    packages = set()
    for line in (notices / "debian-package-provenance.txt").read_text().splitlines():
        binary, version, source, source_version = line.split()
        packages.add((source, source_version))
    for package, version in sorted(packages):
        subprocess.run(["apt-get", "source", "--download-only", f"{package}={version}"], cwd=sources, check=True)
    return [dict(file=p.name, sha256=sha256(p)) for p in sorted(sources.iterdir()) if p.is_file()]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", type=Path, required=True)
    parser.add_argument("--destination", type=Path, required=True)
    parser.add_argument("--archive", type=Path, required=True)
    args = parser.parse_args()
    runtime = args.runtime.resolve()
    destination = args.destination.resolve()
    sources = destination / "sources"
    sources.mkdir(parents=True, exist_ok=True)
    shutil.copytree(runtime / "licenses", destination / "notices-and-recipes", dirs_exist_ok=True)
    repository = Path(__file__).resolve().parents[1]
    shutil.copytree(repository / "tools", destination / "mocktave-packaging-tools", dirs_exist_ok=True,
                    ignore=shutil.ignore_patterns("__pycache__"))
    metadata = json.loads((runtime / "mocktave-runtime.json").read_text())
    target = metadata["target"]
    if "apple-darwin" in target:
        entries = macos(runtime / "licenses", sources)
    elif "linux-gnu" in target:
        entries = linux(runtime / "licenses", sources)
    else:
        raise RuntimeError(f"Source collector does not support {target}")
    (destination / "sources.json").write_text(json.dumps(dict(runtime=metadata, sources=entries), indent=2) + "\n")
    (destination / "README.txt").write_text(
        "Corresponding sources for Mocktave's private Octave runtime.\n\n"
        "sources/ contains upstream source archives and distribution patches.\n"
        "notices-and-recipes/ records the exact installed packages and licenses.\n"
        "For Homebrew, use each retained formula's install method and patches;\n"
        "INSTALL_RECEIPT.json and the SBOM record version/build provenance.\n"
        "For Debian/Ubuntu, unpack the .dsc with dpkg-source -x and use its debian/\n"
        "build rules. Development toolchains are needed to rebuild from source.\n"
        "mocktave-packaging-tools/ contains the subsequent relocation, packaging,\n"
        "and verification scripts. Library paths/signatures are changed by those\n"
        "scripts; the upstream interpreter and numerical source is unmodified.\n"
        "The numerical CLI scope excludes plotting/GUI and external toolchains.\n"
    )
    args.archive.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(args.archive, "w:gz", compresslevel=1) as archive:
        for path in sorted(destination.iterdir()):
            archive.add(path, arcname=path.name)
    print(json.dumps(dict(archive=str(args.archive), sha256=sha256(args.archive), source_files=len(entries))))


if __name__ == "__main__":
    main()
